# Stage 1: Install dependencies
FROM node:22-alpine AS deps
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

# Stage 2: Build the application
FROM node:22-alpine AS builder
WORKDIR /app

# Accept build-time env vars passed via --build-arg (e.g. NEXT_PUBLIC_SITE_ENV)
ARG NEXT_PUBLIC_SITE_ENV
ENV NEXT_PUBLIC_SITE_ENV=$NEXT_PUBLIC_SITE_ENV

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Ensure public/ exists so the runner COPY step never fails on projects that omit it
RUN mkdir -p public

# Fail the build if lint, tests, or build fail
RUN npm run lint \
    && npm test \
    && npm run build

# Stage 3: Minimal production runtime
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production \
    HOSTNAME=0.0.0.0 \
    PORT=8080

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

# Copy the standalone output and required static assets
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 8080

# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
