export const LEAD_SOURCES = [
  "homepage",
  "contact",
  "compare-medicare-options",
  "rx-drug-review",
  "turning-65",
  "turning-65-medicare-spokane",
  "working-past-65-medicare",
  "helping-parent-with-medicare",
  "medicare-appointment-checklist",
  "medicare-plan-review-spokane",
  "medicare-enrollment-resources",
  "medicare-advantage",
  "medicare-supplements",
  "medicare-part-d",
  "supplemental-insurance",
  "advantage-vs-supplement",
  "carriers",
  "testimonials",
  "about",
  "request-contact",
  "medicare-faq",
  "medicare-spokane",
  "medicare-spokane-valley",
  "medicare-liberty-lake",
  "medicare-cheney",
  "medicare-airway-heights",
  "medicare-medical-lake",
  "medicare-mead",
  "medicare-deer-park",
  "review-feedback",
  "unknown",
] as const;

export type LeadSource = (typeof LEAD_SOURCES)[number];
