export type Testimonial = {
  name: string;
  location: string;
  text: string;
  rating: 5;
  source: "Google";
  featured?: boolean;
};

export const testimonials: Testimonial[] = [
  {
    name: "Uletta J.",
    location: "Spokane Area",
    text: "Kristi helped my husband and me find a new Medicare Advantage plan. We appreciated the help and guidance through the process.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Ray L.",
    location: "Spokane Area",
    text: "A very big help. Thank you so much, Cathy.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Marlon C.",
    location: "Spokane Area",
    text: "The service was excellent and professional. I would recommend their services to others.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Catherine S.",
    location: "Spokane Area",
    text: "Everyone we met was super friendly and helpful. Kristi was amazing and very knowledgeable. She made a complex process easier to understand.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Vicki C.",
    location: "Spokane Area",
    text: "Kristi Wright has been amazing to work with in helping my brother find healthcare. I strongly recommend her.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Tim H.",
    location: "Spokane Area",
    text: "Friendly, knowledgeable service. We always enjoy our visit with Kristi. She does a great job.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Diana E.",
    location: "Spokane Area",
    text: "We had an issue with an increase in our insurance premium, and they helped us find a different carrier for less with similar benefits. It was easy and handled quickly.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Steve R.",
    location: "Spokane Area",
    text: "Very knowledgeable and personable. Excellent help.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Jessica M.",
    location: "Spokane Area",
    text: "Kristi was amazing helping me navigate finding the right coverage for my dad. She is a gem.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Dave T.",
    location: "Spokane Area",
    text: "Short but efficient. That's how it should be.",
    rating: 5,
    source: "Google",
  },
  {
    name: "Joan M.",
    location: "Spokane Area",
    text: "Kristi was patient and very knowledgeable. We left with a plan that will work for us and make our healthcare feel less chaotic.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Kathy W.",
    location: "Spokane Area",
    text: "Cathy was knowledgeable, explained my options, answered my questions, and helped me find a supplemental plan that would work for me.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Tim M.",
    location: "Spokane Area",
    text: "Cathy Franklin was super helpful in helping us choose the right health and prescription plans. So much appreciated.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Helen T.",
    location: "Spokane Area",
    text: "Kristi was very professional. She showed me my options and explained different insurance plans. I have recommended her service.",
    rating: 5,
    source: "Google",
  },
  {
    name: "Craig R.",
    location: "Spokane Area",
    text: "Kristi was very helpful and professional for both my wife and me. We will definitely use her next year and refer friends.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Mike S.",
    location: "Spokane Area",
    text: "Very nice and helpful. Thank you, Kristi.",
    rating: 5,
    source: "Google",
  },
  {
    name: "Jan F.",
    location: "Spokane Area",
    text: "I was very impressed with the knowledge and integrity of my broker. A true professional in every way.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Nancy F.",
    location: "Spokane Area",
    text: "She explained everything so that we understood our supplements.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Ed F.",
    location: "Spokane Area",
    text: "Great experience. Very knowledgeable and calming. The stress level was minimal. Great group of people.",
    rating: 5,
    source: "Google",
    featured: true,
  },
  {
    name: "Bradley",
    location: "Spokane Area",
    text: "Easy to work with, very professional, and I would recommend them highly.",
    rating: 5,
    source: "Google",
  },
  {
    name: "Greg W.",
    location: "Spokane Area",
    text: "I was very happy with my experience. They are very knowledgeable and were more than happy to help.",
    rating: 5,
    source: "Google",
  },
  {
    name: "Mark Y.",
    location: "Spokane Area",
    text: "Lynn is a pleasure to work with year after year. Thank you, Lynn.",
    rating: 5,
    source: "Google",
  },
  {
    name: "Julia P.",
    location: "Spokane Area",
    text: "They have been a fantastic resource for wading through the health insurance process.",
    rating: 5,
    source: "Google",
    featured: true,
  },
];
